In [2]:
'''DATA CLEANING'''

from calendar import day_abbr
import requests
import urllib
import json
import csv
# f = open('Desktop/NextMunch/next-munch/json_files/cuisines.json')
# data = json.load(f)
# print(len(data))
url2 = "https://worldwide-restaurants.p.rapidapi.com/search"

dietary_reqs = ['Vegetarian Friendly', 'Vegan Options', 'Gluten Free Options', 'Halal', 'Kosher']
#2nd page
new_url = "https://api.tripadvisor.com/api/internal/1.14/location/186338/restaurants?base_geocodes_on=citymaps&currency=GBP&is_restaurant_filters_v2=true&lang=en_US&limit=50&offset=50&restaurant_tagcategory_standalone=186338&supports_relevance=true"

headers = {
	"content-type": "application/x-www-form-urlencoded",
	"X-RapidAPI-Key": "3b11ee2336msh5791c275fc5dbc6p11fa37jsn3cafb1ed4e82",
	"X-RapidAPI-Host": "worldwide-restaurants.p.rapidapi.com"
}
restaurant_list = ['restaurants']
address_list= ['address']
category_list = ['category']
cuisine_list = ['cuisine']
dietary_list = ['dietary requirements']
phone_list = ['phone No']
price_list = ['price']
rating_list = ['rating']
num_revs_list = ['num_reviews']
index2 = 0
# temp_list = []
new_list = []

def get_API_values(url, header, index):
    print(index)
    if index == 2900:
        f = open('APIvals.csv', 'w')
        for i in range(len(restaurant_list)):
                # string = '{'
                if i == 0:
                    string = f'index;{restaurant_list[i]};{address_list[i]};{category_list[i]};{price_list[i]};{phone_list[i]};{cuisine_list[i]};{dietary_list[i]};{rating_list[i]};{num_revs_list[i]}\n'
                else:
                    string = f'{i-1};{restaurant_list[i]};{address_list[i]};{category_list[i]};{price_list[i]};{phone_list[i]};{cuisine_list[i]};{dietary_list[i]};{rating_list[i]};{num_revs_list[i]}\n'
                # string = f'{dietary_list[i]}\n'
                # string += '},\n'
                f.write(string)
                # f.write('\n')
        
       
        f.close()
        # with open('APIvals.csv', 'a') as file:
        #     writer = csv.writer(file)
    
        #     # for i in range(len(cuisine_list)):
        #     #     string = '{'
        #     #     string += f'"restaurant": "{cuisine_list[i]}", "address": "{address_list[i]}"'
        #     #     string += '},'
        #         # print(string)
        #     writer.writerow(cuisine_list[0])
        #     writer.writerow('\n')

    else:
        
        
        payload = f"offset={index}&language=en_UK&limit=20500&location_id=186338&currency=GBP"
        response = requests.request("POST", url, data=payload, headers=header)
        print(response.status_code)
        if response.status_code != 204 and response.status_code != 504:
        
#             data = json.load(read_file)['results']['data']
            data = json.loads(response.text)['results']['data']
            for i in range(len(data)):
                # index = str(i)
                # print(data[index]['cuisine'])
                restaurant = data[i]['name']
                address = data[i]['address_obj']['street1']
                category = data[i]['category']['name']
                cuisine = data[i]['cuisine']
                rating = data[i]['rating']
                num_reviews = data[i]['num_reviews']
                try:
                    price = data[i]['price']
                    phone_number = data[i]['phone']
                except KeyError:
                    price = data[i]['price_level'].strip()
                    phone_number = 'NULL'

                if restaurant not in restaurant_list:
                    address_list.append(address)
                    restaurant_list.append(restaurant)
                    category_list.append(category)
                    phone_list.append(phone_number)
                    rating_list.append(rating)
                    num_revs_list.append(num_reviews)

                    number_price = []
                    temp_str = ''
                    for i in range(len(price)):
                        # print(price[i], i)
                        # print(price[len(price)-1])

                        if price[i].isdigit() == True:
                            if i == len(price)-1:
                                if price[i-1].isdigit() == False:
                                    number_price.append(str(price[i]))

                                else:
                                    pass
                            elif price[i].isdigit() and price[i+1].isdigit():
                                number_price.append(str(price[i])+ str(price[i+1]))
                            elif price[i].isdigit() and price[i-1].isdigit() == True:
                                pass
                            elif price[i].isdigit() and price[i+1].isdigit() == False:
                                number_price.append(str(price[i]))

                            else:
                                pass
                                # print(temp_str)
                        else:
                            pass


                    print(number_price)
                    # number_price = 0
                    if len(number_price) == 0:
                        final = 0
                    elif len(number_price) == 1:
                        final = int(number_price[0])
                    else:
                        final = int(number_price[0])+int(number_price[1])//2

                    price_list.append(final)
                    cuisine_temp_list = []
                    dietary_temp_list = []
                    for i in range(len(cuisine)-1):

                        if cuisine[i]['name'] not in dietary_reqs:
                            cuisine_temp_list.append(cuisine[i]['name'])
                        else:
                            dietary_temp_list.append(cuisine[i]['name'])

                    cuisine_list.append(cuisine_temp_list)
                    dietary_list.append(dietary_temp_list)

                    break

                    # temp_list = []


                    # for i in range(len(cuisine)):
                    #     temp[]
                    #     dietary_list.append(i['name'])
                        # print(i['name'])
               


            get_API_values(url, header, index+1)
            
        else:
            get_API_values(url, header, index+1)
#             pass


get_API_values(url2, headers, index2)

#     for cuisine in cuisines:

#             cuisine_list.append(cuisine['name'])

        # string=''
    
    # print('{cuisine: {csn}},').format(csn = cuisine_list[i])


0
200
['5', '9']
1
200
['18', '27']
2
200
['1', '8']
3
200
['5', '8']
4
200
[]
5
200
['27', '68']
6
200
['9', '27']
7
200
['14', '18']
8
200
[]
9
200
['5', '23']
10
200
[]
11
200
['4', '7']
12
200
['1', '14']
13
200
['6', '23']
14
200
[]
15
200
['30', '86']
16
200
[]
17
200
['9', '15']
18
200
['9', '27']
19
200
[]
20
200
[]
21
200
[]
22
200
[]
23
200
['6', '36']
24
200
[]
25
200
['27', '45']
26
200
[]
27
200
['18', '54']
28
200
['9', '27']
29
200
[]
30
200
['14', '36']
31
200
['17']
32
200
['14', '27']
33
200
[]
34
200
['5', '18']
35
200
['5', '50']
36
200
[]
37
200
['9', '21']
38
200
[]
39
200
['23', '36']
40
200
['5', '14']
41
200
['5', '15']
42
200
['14', '32']
43
200
['5', '14']
44
200
['9', '36']
45
200
['5', '16']
46
200
['2', '7']
47
200
['6', '20']
48
200
['18', '27']
49
200
[]
50
200
['41', '90']
51
200
[]
52
200
['3', '9']
53
200
['18', '41']
54
200
[]
55
200
[]
56
200
[]
57
200
['5', '40']
58
200
[]
59
200
[]
60
200
['27', '72']
61
200
['2', '9']
62
200
[]
63
200
['18', '45'

SSLError: HTTPSConnectionPool(host='worldwide-restaurants.p.rapidapi.com', port=443): Max retries exceeded with url: /search (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

In [14]:
import numpy as np
import difflib
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
df = pd.read_excel("APIvals.xlsx", index_col = None)
df
# import pip
# pip3 install sklearn


index                   restaurants  \
0         0  Devine Restaurant Coffee Bar   
1         1            Bonoo Indian Tapas   
2         2                     Nora Cafe   
3         3                         Hibox   
4         4                   Indian Room   
...     ...                           ...   
2848   2848         Nancy Lam's Enak Enak   
2849   2849               The Goat Tavern   
2850   2850              Haidilao Hot Pot   
2851   2851                   Neat Burger   
2852   2852                 Edgar Wallace   

                                   address    category  price  \
0                           19 Vine Street  Restaurant      9   
1                        675 Finchley Road  Restaurant     31   
2                       9 Wentworth Street  Restaurant      5   
3                         48 Goodge Street  Restaurant      9   
4                          59 Bedford Hill  Restaurant      0   
...                                    ...         ...    ...   
2848                      56 Lavender Hill  Restaurant     61   
2849                     3 Stafford Street  Restaurant     12   
2850  Greenwich Peninsula Peninsula Square  Restaurant      0   
2851                      4 Princes Street  Restaurant      0   
2852                       40 Essex Street  Restaurant      0   

              phone No                                            cuisine  \
0     +44 20 7488 9929                    ['Cafe', 'European', 'British']   
1     +44 20 7794 8899  ['Wine Bar', 'Indian', 'Contemporary', 'Street...   
2     +44 20 7247 4992                       ['Cafe', 'British', 'Grill']   
3     +44 20 7580 9312  ['Lebanese', 'Mediterranean', 'Middle Eastern'...   
4                  NaN                                         ['Indian']   
...                ...                                                ...   
2848  +44 20 7924 3148                            ['Indonesian', 'Asian']   
2849  +44 20 7629 0966                          ['Bar', 'British', 'Pub']   
2850               NaN                    ['Chinese', 'Asian', 'Healthy']   
2851               NaN                                      ['Fast food']   
2852               NaN                          ['Bar', 'British', 'Pub']   

                                   dietary requirements  rating  num_reviews  \
0              ['Vegan Options', 'Gluten Free Options']     5.0          295   
1              ['Vegetarian Friendly', 'Vegan Options']     5.0         1713   
2                               ['Vegetarian Friendly']     5.0          264   
3     ['Vegetarian Friendly', 'Vegan Options', 'Halal']     5.0          212   
4     ['Vegetarian Friendly', 'Vegan Options', 'Halal']     5.0         1788   
...                                                 ...     ...          ...   
2848                                                 []     4.5          134   
2849                                                 []     4.0          132   
2850                            ['Vegetarian Friendly']     5.0           31   
2851           ['Vegetarian Friendly', 'Vegan Options']     4.5           92   
2852                                                 []     4.5          122   

      rating_actual  
0         59.000000  
1        342.600000  
2         52.800000  
3         42.400000  
4        357.600000  
...             ...  
2848      29.777778  
2849      33.000000  
2850       6.200000  
2851      20.444444  
2852      27.111111  

[2853 rows x 11 columns]

In [15]:
# Address change from postcode to text descriptor
# add jageh ka link
# df
# selected_features = ['cuisine','dietary requirements', 'price', 'address']

# df['dietary requirements'] = df['dietary requirements'].fillna('')
combined_features = df['cuisine'] + ' ' + str(df['price']) + ' ' + df['dietary requirements'] + ' ' + str(df['address'])
print(combined_features) 
# df.head()

0       ['Cafe', 'European', 'British'] 0        9\n1 ...
1       ['Wine Bar', 'Indian', 'Contemporary', 'Street...
2       ['Cafe', 'British', 'Grill'] 0        9\n1    ...
3       ['Lebanese', 'Mediterranean', 'Middle Eastern'...
4       ['Indian'] 0        9\n1       31\n2        5\...
                              ...                        
2848    ['Indonesian', 'Asian'] 0        9\n1       31...
2849    ['Bar', 'British', 'Pub'] 0        9\n1       ...
2850    ['Chinese', 'Asian', 'Healthy'] 0        9\n1 ...
2851    ['Fast food'] 0        9\n1       31\n2       ...
2852    ['Bar', 'British', 'Pub'] 0        9\n1       ...
Length: 2853, dtype: object


In [16]:
vectorizer = TfidfVectorizer()

In [17]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [18]:
print(feature_vectors)

  (0, 110)	0.07406605499619946
  (0, 15)	0.07406605499619946
  (0, 58)	0.07406605499619946
  (0, 9)	0.07406605499619946
  (0, 122)	0.07406605499619946
  (0, 140)	0.07406605499619946
  (0, 113)	0.14813210999239892
  (0, 74)	0.07406605499619946
  (0, 142)	0.07406605499619946
  (0, 93)	0.07406605499619946
  (0, 11)	0.07406605499619946
  (0, 79)	0.14813210999239892
  (0, 32)	0.07406605499619946
  (0, 12)	0.07406605499619946
  (0, 72)	0.07406605499619946
  (0, 10)	0.07406605499619946
  (0, 160)	0.07406605499619946
  (0, 125)	0.07406605499619946
  (0, 62)	0.07406605499619946
  (0, 14)	0.07406605499619946
  (0, 144)	0.4443963299771968
  (0, 158)	0.07406605499619946
  (0, 1)	0.07406605499619946
  (0, 65)	0.3519459083056515
  (0, 71)	0.3519459083056515
  :	:
  (2852, 12)	0.08906490721493646
  (2852, 72)	0.08906490721493646
  (2852, 10)	0.08906490721493646
  (2852, 160)	0.08906490721493646
  (2852, 125)	0.08906490721493646
  (2852, 62)	0.08906490721493646
  (2852, 14)	0.08906490721493646
  (2852

In [19]:
similarity = cosine_similarity(feature_vectors)

In [20]:
print(similarity)

[[1.         0.60450601 0.7552302  ... 0.62775406 0.67054702 0.72131143]
 [0.60450601 1.         0.66392967 ... 0.63834927 0.77152922 0.72862141]
 [0.7552302  0.66392967 1.         ... 0.73170133 0.73519355 0.81761402]
 ...
 [0.62775406 0.63834927 0.73170133 ... 1.         0.70686744 0.75487829]
 [0.67054702 0.77152922 0.73519355 ... 0.70686744 1.         0.75848113]
 [0.72131143 0.72862141 0.81761402 ... 0.75487829 0.75848113 1.        ]]


In [21]:
# df.groupby('restaurants')['rating_actual'].count().head()
# df.sort_values(['rating_actual'],ascending=False).groupby('restaurants').head()

ratings = pd.DataFrame(df.sort_values(['rating_actual'],ascending=False).groupby('restaurants').head())
ratings

index                              restaurants  \
2565   2565                               Aqua Shard   
2693   2693                    London Steakhouse Co.   
1051   1051  OXO Tower Restaurant, Bar and Brasserie   
850     850                           Hard Rock Cafe   
1687   1687                             The Wolseley   
...     ...                                      ...   
2467   2467                                   Mina's   
2503   2503                    Golden Tea Shoreditch   
2490   2490               How Matcha Cafe Marylebone   
2829   2829                                      Uva   
2653   2653                        Chamuyo Bayswater   

                                            address    category  price  \
2565                           31 St. Thomas Street  Restaurant      0   
2693      University House 109-117 Middlesex Street  Restaurant     26   
1051  Oxo Tower Wharf Barge House Street South Bank  Restaurant     16   
850                               150 Old Park Lane  Restaurant     45   
1687                                 160 Piccadilly  Restaurant     52   
...                                             ...         ...    ...   
2467                              20 Motcomb Street  Restaurant      0   
2503                                96 Curtain Road  Restaurant      0   
2490                            47 Blandford Street  Restaurant      5   
2829                             139 Bellenden Road  Restaurant     29   
2653                              66 Inverness Mews  Restaurant      0   

              phone No                                            cuisine  \
2565               NaN            ['European', 'British', 'Contemporary']   
2693  +44 20 7247 5050                          ['Steakhouse', 'British']   
1051  +44 20 7803 3888  ['Bar', 'Pub', 'Wine Bar', 'European', 'Contem...   
850   +44 20 7514 1700            ['American', 'Bar', 'Central American']   
1687  +44 20 7499 6996                            ['European', 'British']   
...                ...                                                ...   
2467               NaN             ['Italian', 'French', 'Mediterranean']   
2503               NaN                                                 []   
2490   +44 7984 813267                                                 []   
2829  +44 20 3149 1652  ['Bar', 'Mediterranean', 'European', 'Portugue...   
2653               NaN  ['Steakhouse', 'Latin', 'Spanish', 'Argentinian']   

                          dietary requirements  rating  num_reviews  \
2565  ['Vegetarian Friendly', 'Vegan Options']     4.0        16985   
2693                   ['Vegetarian Friendly']     4.0        15605   
1051                   ['Vegetarian Friendly']     4.5         9725   
850   ['Vegetarian Friendly', 'Vegan Options']     4.0         8419   
1687                   ['Vegetarian Friendly']     4.0         7886   
...                                        ...     ...          ...   
2467                                        []     5.0           29   
2503                                        []     5.0           29   
2490                                        []     5.0           28   
2829                                        []     5.0           27   
2653                                        []     5.0           26   

      rating_actual  
2565    4246.250000  
2693    3901.250000  
1051    2161.111111  
850     2104.750000  
1687    1971.500000  
...             ...  
2467       5.800000  
2503       5.800000  
2490       5.600000  
2829       5.400000  
2653       5.200000  

[2853 rows x 11 columns]

In [12]:
# plt.figure
ratings['rating_actual'].hist(bins=70)

NameError: name 'ratings' is not defined